import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import PAHeader from "@/app/components/PAHeader";
import PAFooter from "./components/PAFooter";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`flex min-h-screen flex-col ${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <PAHeader />
        <div className="flex-1 flex">
          {children}
        </div>
        <PAFooter />
      </body>
    </html>
  );
}
